[package]
name = "shuffle"
version = "0.1.0"
authors = ["Atsushi Nakayasu <ankysp@gmail.com>"]

[dependencies]

[lib]
name = "src"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
